### ISSUE TITLE
🙌 Wrong warning message when listing on unemeta.com

### ISSUE THREAD

**Issue by 3lang3** [RevokeCash/browser-extension#20]
Our website is not in [AllowList](https://github.com/RevokeCash/browser-extension/blob/master/src/lib/constants.ts#L52-L53), and, our nft listing logic matched this [code](https://github.com/RevokeCash/browser-extension/blob/d49f1de92003681b9e768782f54e734a52a5d975/src/lib/utils.ts#L101-L107), It causes the error message displayed on ui, which makes users feel quite confused.
I also check this #12, Hope to add support for unemeta.com

<img width="480" alt="image" src="https://user-images.githubusercontent.com/7098719/197426773-d9f60580-d95d-4e0e-992a-17e87082392c.png">

**Comment by rkalis** [comment]
Thanks! I'll have to add contract address checks to the signature rather than just looking at the structure of the message. Should be do-able. Thanks for the report, will try to get this done soon.

**Comment by rkalis** [comment]
Do you know the `verifyingContract` address for unemeta?

**Comment by 3lang3** [comment]
> Do you know the `verifyingContract` address for unemeta?

0x2445A4E934AF7C786755931610Af099554Ba1354

**Comment by rkalis** [comment]
This has been fixed in 0.2.6
